# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true

# Project properties
group=dev.lambdaurora.lambdynamiclights
base_version=4.12.3
java_version=25

# Mod Properties
archives_base_name = lambdynamiclights
compatible_mc_versions=
fabric_mc_constraints=~26.2-
neoforge_mc_constraints=[26.2,)
modrinth_id=yBW8D80W
curseforge_id=393442

fabric.loom.dropNonIntermediateRootMethods=true
