# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true

# Project properties
group=dev.lambdaurora.lambdynamiclights
base_version=4.11.0
java_version=25

# Mod Properties
archives_base_name = lambdynamiclights
compatible_mc_versions=26.1,26.1.1
fabric_mc_constraints=~26.1-
neoforge_mc_constraints=[26.1,)
modrinth_id=yBW8D80W
curseforge_id=393442

fabric.loom.dropNonIntermediateRootMethods=true
