[versions]
minecraft = "26.1.2"
fabric-loader = "0.18.4"
fabric-api = "0.152.1+26.1.2"
neoforge-loader = "11.0.0"
neoforge-api = "26.1.2.71"
mappings-parchment = "2024.07.28"

# Dependencies
yumi-commons = "2.0.0"
yumi-mc-foundation = "1.1.0+26.1"
spruceui = "10.0.0+26.1"
pridelib = "1.6.0+26.1"

modmenu = "18.0.0-beta.1"
trinkets = "4.0.0-beta.2+26.1"
accessories = "1.3.3-beta+1.21.8"
sodium = "0.8.12+mc26.1.2"

# Configuration
nightconfig = "3.8.1"

# Gradle
gradle-licenser = "4.0.+"
gradle-loom = "1.16.+"
gradle-lambdamcdev = "2.2.0"
gson = "2.11.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }
neoforge-api = { module = "net.neoforged:neoforge", version.ref = "neoforge-api" }

# Dependencies
yumi-commons-core = { module = "dev.yumi.commons:yumi-commons-core", version.ref = "yumi-commons" }
yumi-commons-collections = { module = "dev.yumi.commons:yumi-commons-collections", version.ref = "yumi-commons" }
yumi-commons-event = { module = "dev.yumi.commons:yumi-commons-event", version.ref = "yumi-commons" }
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
pridelib = { module = "io.github.queerbric:pridelib", version.ref = "pridelib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
trinkets = { module = "eu.pb4:trinkets", version.ref = "trinkets" }
accessories = { module = "io.wispforest:accessories-fabric", version.ref = "accessories" }
sodium-api = { module = "net.caffeinemc:sodium-neoforge-api", version.ref = "sodium" }

# Configuration
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

# Gradle
gradle-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "gradle-licenser" }
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
