[versions]
minecraft = "1.21.1"
fabric-loader = "0.18.4"
fabric-api = "0.105.0+1.21.1"
neoforge-loader = "7.0.11"
mappings-yalmm = "6"
mappings-parchment = "2024.07.28"

# Dependencies
yumi-commons = "1.0.0"
yumi-mc-foundation = "1.0.0-beta.1+1.21.1"
spruceui = "6.2.5+1.21.1"
pridelib = "1.2.4+1.21.1"

modmenu = "11.0.3"
trinkets = "3.10.0"
accessories = "1.1.0-beta.16+1.21.1"
sodium = "0.8.12-beta.1+mc1.21.1"

# Configuration
nightconfig = "3.8.1"

# Gradle
gradle-licenser = "4.0.+"
gradle-loom = "1.16.+"
gradle-lambdamcdev = "1.10.+"
gson = "2.11.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
neoforge-loader = { module = "net.neoforged.fancymodloader:loader", version.ref = "neoforge-loader" }

# Dependencies
yumi-commons-core = { module = "dev.yumi.commons:yumi-commons-core", version.ref = "yumi-commons" }
yumi-commons-collections = { module = "dev.yumi.commons:yumi-commons-collections", version.ref = "yumi-commons" }
yumi-commons-event = { module = "dev.yumi.commons:yumi-commons-event", version.ref = "yumi-commons" }
yumi-mc-foundation = { module = "dev.yumi.mc.core:yumi-mc-foundation", version.ref = "yumi-mc-foundation" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
pridelib = { module = "io.github.queerbric:pridelib", version.ref = "pridelib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }
accessories = { module = "io.wispforest:accessories-fabric", version.ref = "accessories" }
sodium-api = { module = "net.caffeinemc:sodium-fabric-api", version.ref = "sodium" }

# Configuration
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

# Gradle
gradle-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "gradle-licenser" }
gradle-loom = { module = "net.fabricmc:fabric-loom", version.ref = "gradle-loom" }
gradle-lambdamcdev = { module = "dev.lambdaurora.mcdev:dev.lambdaurora.mcdev.gradle.plugin", version.ref = "gradle-lambdamcdev" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
